spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pensieve?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 111111
    druid:
      maxActive: 50
      max-wait: 2000
      min-idle: 5
      initial-size: 5
      removeAbandoned: true
      removeAbandonedTimeout: 60
      logAbandoned: true
      stat-view-servlet:
        enabled: true
      web-stat-filter:
        enabled: true
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000l
      use-global-data-source-stat: true
  session:
    store-type: jdbc
  jackson:
    time-zone: GMT+8
  freemarker:
    check-template-location: false
  mvc:
    throw-exception-if-no-handler-found: true
server:
  servlet:
    context-path: /
    session:
      cookie:
        name: SESSIONID
      timeout: 60m
  port: 64081
elastic:
  security:
    administrators:
      - E2FA5835B14E47E6BDD04C3BFFB75D2B
    patterns:
      - /**
    excepts:
      - /
      - /home
      - /api/**
      - /pensieve/account/_csrf
      - /security/getRouter
      - /security/login/**
      - /security/logout
      - /i18n/phrase/getTransByLangNo
      - /accessory/**
    origin:
      - "*"
    csrf-excepts:
      - /druid/**/*.json